AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Cloud-Native E-commerce PoC Backend API (EcomPoc)

# เราจะใช้ Parameter นี้เพื่อ "ส่ง" User Pool ID ที่เราคัดลอกมา
Parameters:
  CognitoUserPoolId:
    Type: String
    Description: "The ID of the Cognito User Pool (e.g., ap-southeast-1_xxxxx)"
  CognitoAppClientId:
    Type: String
    Description: "The App Client ID of the Cognito User Pool (e.g., xxxxxxxxxxxxxxx)"

# Global settings สำหรับทุก Function ในไฟล์นี้
Globals:
  Function:
    Timeout: 10
    Runtime: python3.12 # <-- อัปเดตตาม Python 3.12.0 ของคุณ
    MemorySize: 128
    Architectures:
      - x86_64 # หรือ arm64 ถ้าคุณใช้ Mac M1/M2/M3

Resources:
  # 1. API Gateway (แบบ HTTP API เพื่อ Free Tier)
  EcommerceHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration: # อนุญาตให้ React App (localhost) เรียก API นี้ได้
        AllowOrigins:
          - "http://localhost:5173" # Port ของ Vite (React)
          - "http://localhost:3000" # Port React ทั่วไป
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        MaxAge: "3600"
      # นี่คือการสร้าง "ยาม" (Authorizer)
      Auth:
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPoolId}"
              audience:
                - !Ref CognitoAppClientId
                # (ในอนาคตเราจะเพิ่ม 'audience' ที่นี่ แต่ตอนนี้เอาแค่นี้ก่อน)

  # DynamoDB Table สำหรับสินค้า
  ProductsTable:
    Type: AWS::Serverless::SimpleTable # SAM จะสร้าง Table แบบง่ายๆ ให้
    Properties:
      TableName: EcomPoc-ProductsTable # ตั้งชื่อ Table
      PrimaryKey:
        Name: ProductID # บอกว่า PK คือฟิลด์ชื่อ ProductID
        Type: String
      ProvisionedThroughput: # ตั้งค่าความเร็ว (อยู่ใน Free Tier)
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # 2. Lambda Function สำหรับ Product Service
  ProductServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/product_service/ # บอก SAM ว่าโค้ดอยู่ที่ไหน
      Handler: app.main.handler # ชี้ไปที่: (ไฟล์ app/main.py) . (ตัวแปร handler)
      Events:
        GetProductEvent: # 1. GET (Read)
          Type: HttpApi
          Properties:
            ApiId: !Ref EcommerceHttpApi
            Path: /products/{product_id}
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
        UpdateProductEvent: # 2. PUT (Update)
          Type: HttpApi
          Properties:
            ApiId: !Ref EcommerceHttpApi
            Path: /products/{product_id}
            Method: PUT
            Auth:
              Authorizer: CognitoAuthorizer
        DeleteProductEvent: # 3. DELETE
          Type: HttpApi
          Properties:
            ApiId: !Ref EcommerceHttpApi
            Path: /products/{product_id}
            Method: DELETE
            Auth:
              Authorizer: CognitoAuthorizer

        ListProductsEvent: # 4. GET (List)
          Type: HttpApi
          Properties:
            ApiId: !Ref EcommerceHttpApi
            Path: /products
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
        CreateProductEvent: # 5. POST (Create)
          Type: HttpApi
          Properties:
            ApiId: !Ref EcommerceHttpApi
            Path: /products
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

      # เพิ่ม Policy ให้ Lambda Function
      Policies:
        # ให้สิทธิ์ Lambda ในการ (Create, Read, Update, Delete) กับ Table
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable # ระบุว่าให้สิทธิ์เฉพาะ Table นี้

      Environment: # ส่งชื่อ Table เข้าไปในโค้ด Python
        Variables:
          DYNAMO_TABLE_NAME: !Ref ProductsTable

Outputs:
  # แสดง URL ของ API เมื่อ Deploy เสร็จ
  ApiEndpoint:
    Description: "API Gateway Endpoint URL"
    Value: !Sub "https://${EcommerceHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
